// <auto-generated />
namespace MMO_Mania.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class leaderboard2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(leaderboard2));
        
        string IMigrationMetadata.Id
        {
            get { return "202104292359088_leaderboard2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
